[package]
name = "cargo-makepad"
version = "0.4.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad cargo extension"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "3q9p7hJP7S16AZ2sa6ONkcZPa0w="

[dependencies]
makepad-miniz = { path = "../../libs/miniz", version = "0.4.0" }
#makepad-networking = { path = "../../libs/networking", version = "0.4.0" }
makepad-shell = { path = "../../libs/shell", version = "0.4.0" }

[features]
nightly=[]